name: Host Tests CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtest-dev doxygen

      - name: Compile and Run Tests
        run: make test

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: docs/html/
